id: oauth_app_creation
learningObjectives:
  - Create an OAuth app and retrieve the client ID.
hints:
  - In your Wix Headless CMS dashboard, navigate to the Settings > Headless Settings

startFlow:
  do:
    - actionId: bot_message
      params:
        person: lucca
        messages:
          - text: Great! Now, let's set up secure access. In order to start working we need you to connect to your Wix app.
          - components:
            - type: wix_connect
trigger:
  type: user_event
  params:
    event: wix_user_connected
  flowNode:
    do:
      - actionId: wix_load_data
        params:
          dataPath: "assets/data.json"
      - actionId: bot_message
        params:
          person: lucca
          messages:
          - text: "![](https://i.giphy.com/media/Jir7AUookJHIVb5aYM/giphy.gif) </br> Great job with the setup, I already see that you have some data in the 'Our Team' collection. Ready for the next challenge?"
      - actionId: finish_step
