id: env_local_setup
learningObjectives:
  - Configure the application ID in the local environment.
hints:
  - Edit the .env.local file in your project.
  - Add the Wix app ID to this file and save the changes.
startFlow:
  do:
    - actionId: bot_message
      params:
        person: lucca
        messages:
          - text: "Alright, time to get our app talking to Wix! You've got a template environment file named `.env.template`. Copy it to create a `.env.local` file, :instruction[then add the Wix app ID there]. After that, open the app and check if you can see the data on the website. Let me know how it goes!"
    - actionId: ready_message
      params:
        person: lucca
trigger:
  type: user_ready_response
  flowNode:
    do:
      - actionId: bot_message
        params:
          person: lucca
          messages:
          - text: "Awesome, you're making it look easy! Seeing the data means everything's connected perfectly."
      - actionId: finish_step
